[build]
base = "frontend"
command = "yarn build"
publish = "build"
functions = "../netlify/functions"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/.netlify/functions/*"
[headers.values]
Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
